import type { Subscription } from "@/types/subscription";

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "1",
    name: "래미안 원베일리",
    type: "민간분양",
    region: "서울 서초구",
    address: "서초구 반포동 18-1",
    totalUnits: 2990,
    units: [
      { area: 59, price: 120000, count: 500 },
      { area: 84, price: 170000, count: 1200 },
      { area: 114, price: 240000, count: 800 },
    ],
    schedule: {
      announcementDate: "2026-04-01",
      specialStartDate: "2026-04-10",
      firstPriorityDate: "2026-04-11",
      secondPriorityDate: "2026-04-12",
      resultDate: "2026-04-18",
    },
    conditions: {
      needsAccount: true,
      minDeposit: 1500,
      needsHomeless: false, // 민간은 비규제지역이면 무관
      needsHouseholder: false,
    },
    specialTypes: ["일반", "신혼부부", "생애최초", "다자녀"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "마포 프레스티지자이",
    type: "공공분양",
    region: "서울 마포구",
    address: "마포구 아현동 618",
    totalUnits: 3500,
    units: [
      { area: 49, price: 55000, count: 800 },
      { area: 59, price: 72000, count: 1500 },
      { area: 74, price: 90000, count: 1200 },
    ],
    schedule: {
      announcementDate: "2026-03-28",
      specialStartDate: "2026-04-05",
      firstPriorityDate: "2026-04-06",
      secondPriorityDate: "2026-04-07",
      resultDate: "2026-04-14",
    },
    conditions: {
      needsAccount: true,
      accountMonths: 6,
      accountPayments: 6,
      needsHomeless: true,
      needsHouseholder: false,
      incomeLimit: 100, // 도시근로자 100%
      assetLimit: 37900,
    },
    specialTypes: ["일반", "청년", "신혼부부", "생애최초", "다자녀", "노부모부양"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "강동 신혼희망타운",
    type: "신혼희망타운",
    region: "서울 강동구",
    address: "강동구 둔촌동 170",
    totalUnits: 1200,
    units: [
      { area: 46, price: 38000, count: 400 },
      { area: 59, price: 52000, count: 500 },
      { area: 74, price: 68000, count: 300 },
    ],
    schedule: {
      announcementDate: "2026-04-15",
      specialStartDate: "2026-04-22",
      firstPriorityDate: "2026-04-23",
      resultDate: "2026-05-02",
    },
    conditions: {
      needsAccount: true,
      accountMonths: 6,
      accountPayments: 6,
      needsHomeless: true,
      needsHouseholder: false,
      incomeLimit: 130,
      assetLimit: 37900,
      needsMarried: true,
      marriageYears: 7,
    },
    specialTypes: ["신혼부부"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "노원 청년주택",
    type: "청년특별공급",
    region: "서울 노원구",
    address: "노원구 상계동 330",
    totalUnits: 800,
    units: [
      { area: 36, price: 22000, count: 500 },
      { area: 46, price: 30000, count: 300 },
    ],
    schedule: {
      announcementDate: "2026-04-03",
      specialStartDate: "2026-04-12",
      resultDate: "2026-04-20",
    },
    conditions: {
      needsAccount: true,
      accountMonths: 6,
      accountPayments: 6,
      needsHomeless: true,
      needsHouseholder: false,
      incomeLimit: 140,
      ageRange: { min: 19, max: 39 },
      needsSingle: true,
    },
    specialTypes: ["청년"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "은평 행복주택",
    type: "행복주택",
    region: "서울 은평구",
    address: "은평구 응암동 98",
    totalUnits: 600,
    units: [
      { area: 26, price: 8000, count: 300 },
      { area: 36, price: 12000, count: 300 },
    ],
    schedule: {
      announcementDate: "2026-04-10",
      specialStartDate: "2026-04-18",
      resultDate: "2026-04-28",
    },
    conditions: {
      needsAccount: false, // 행복주택은 청약통장 불필요
      needsHomeless: true,
      needsHouseholder: false,
      incomeLimit: 100,
      ageRange: { min: 19, max: 39 },
      notes: "대학생, 청년, 신혼부부 대상",
    },
    specialTypes: ["청년", "신혼부부"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "힐스테이트 청담",
    type: "민간분양",
    region: "서울 강남구",
    address: "강남구 청담동 52",
    totalUnits: 640,
    units: [
      { area: 84, price: 195000, count: 300 },
      { area: 112, price: 280000, count: 340 },
    ],
    schedule: {
      announcementDate: "2026-04-05",
      specialStartDate: "2026-04-14",
      firstPriorityDate: "2026-04-15",
      secondPriorityDate: "2026-04-16",
      resultDate: "2026-04-22",
    },
    conditions: {
      needsAccount: true,
      minDeposit: 1500,
      needsHomeless: false,
      needsHouseholder: false,
    },
    specialTypes: ["일반", "신혼부부", "생애최초"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "성수 오피스텔 리브",
    type: "오피스텔",
    region: "서울 성동구",
    address: "성동구 성수동2가 315",
    totalUnits: 420,
    units: [
      { area: 24, price: 32000, count: 200 },
      { area: 33, price: 44000, count: 220 },
    ],
    schedule: {
      announcementDate: "2026-04-08",
      firstPriorityDate: "2026-04-17",
      resultDate: "2026-04-24",
    },
    conditions: {
      needsAccount: false, // 오피스텔은 통장 불필요
      needsHomeless: false,
      needsHouseholder: false,
    },
    specialTypes: ["일반"],
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "송파 국민임대",
    type: "국민임대",
    region: "서울 송파구",
    address: "송파구 가락동 201",
    totalUnits: 500,
    units: [
      { area: 36, price: 5000, count: 250 },
      { area: 46, price: 7000, count: 250 },
    ],
    schedule: {
      announcementDate: "2026-04-20",
      specialStartDate: "2026-04-28",
      resultDate: "2026-05-08",
    },
    conditions: {
      needsAccount: true,
      accountMonths: 6,
      accountPayments: 6,
      needsHomeless: true,
      needsHouseholder: false,
      incomeLimit: 70, // 도시근로자 70%
      assetLimit: 37900,
    },
    specialTypes: ["일반", "청년", "신혼부부"],
    fetchedAt: new Date().toISOString(),
  },
];
